# Generated by Django 4.2.4 on 2023-08-05 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('TANKS', 'Танки'), ('HILS', 'Хилы'), ('DD', 'ДД'), ('MERCHANTS', 'Торговцы'), ('GUILDMASTERS', 'Гилдиамтеры'), ('QUESTSGIVERS', 'Квестгиверы'), ('BLACKSMITHS', 'Кузнецы'), ('TANNERS', 'Кожевники'), ('POTIONMAKERS', 'Зельевары'), ('SPELLCASTERS', 'Мастера заклинаний')], default='', max_length=64)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('postImage', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('postFile', models.FileField(blank=True, null=True, upload_to='file/')),
                ('avthor', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.post')),
                ('userEditor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
