# Generated by Django 4.2.4 on 2023-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_parent_comment_reply_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='status',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=models.TextField(null=True),
        ),
    ]
